// Home
export const GET_CHARACTERS = "GET_CHARACTERS"
export const GET_CHARACTERS_SUCCESS = "GET_CHARACTERS_SUCCESS"
export const GET_CHARACTERS_FAIL = "GET_CHARACTERS_FAIL"

// Edit
export const GET_CHARACTER = "UPDATE_CHARACTER"
export const UPDATE_CHARACTER_INIT = "UPDATE_CHARACTER_INIT"
export const UPDATE_CHARACTER_SUCCESS = "UPDATE_CHARACTER_SUCCESS"
export const UPDATE_CHARACTER_FAIL = "UPDATE_CHARACTER_FAIL"

// New
export const ADD_CHARACTER = "ADD_CHARACTER"
export const ADD_CHARACTER_SUCCESS = "ADD_CHARACTER_SUCCESS"
export const ADD_CHARACTER_FAIL = "ADD_CHARACTER_FAIL"

// Delete
export const GET_CHARACTER_DELETE = "GET_CHARACTER_DELETE"
export const CHARACTER_DELETE_SUCCESS ="CHARACTER_DELETE_SUCCESS"
export const CHARACTER_DELETE_FAIL ="CHARACTER_DELETE_FAIL"

